module.exports = {
  color: {
    border: { value: "{palette.border.value}" },
    borderDark: { value: "{palette.borderDark.value}" },
    focus: { value: "{palette.focus.value}" },
    heading: { value: "{palette.heading.value}" },
    hero: { value: "{palette.hero.value}" },
    light: { value: "{palette.light.value}" },
    link: { value: "{palette.link.value}" },
    muted: { value: "{palette.muted.value}" },
    neutral: { value: "{palette.neutral.value}" },
    pop: { value: "{palette.pop.value}" },
    primary: { value: "{palette.primary.value}" },
    text: { value: "{palette.text.value}" },
    info: { value: "{palette.info.value}" },
    warning: { value: "{palette.warning.value}" },
    danger: { value: "{palette.danger.value}" },
    system: { value: "{palette.system.value}" },
  },
};
