import Head from 'next/head';

import wbc from '../../../build/js/wbc';
import stg from '../../../build/js/stg';
import bom from '../../../build/js/bom';
import bsa from '../../../build/js/bsa';
import rams from '../../../build/js/rams';

import { PackTable, TableRow } from '@/components/PackTable';
import Link from 'next/link';

const themes = {
	wbc,
	stg,
	bom,
	bsa,
	rams,
};

export default function Home() {
	const packNames = Object.keys(wbc.color) as (keyof typeof wbc.color)[];

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div
				style={{
					display: 'flex',
					gap: '3rem',
					flexDirection: 'column',
					fontFamily: 'Arial, Helvetica, sans-serif',
				}}
			>
				<h1>Tokens</h1>

				<Link href={'/theme'}>Themes</Link>
				{packNames.sort().map((pack) => {
					const tableData: TableRow[] = [];
					const tokenNames = Object.keys(wbc.color[pack]);

					tokenNames.forEach((token) => {
						tableData.push({
							token: token,
							varName: wbc.color[pack][token].name,
							wbc: wbc.color[pack][token].value,
							stg: stg.color[pack][token].value,
							bom: bom.color[pack][token].value,
							bsa: bsa.color[pack][token].value,
							rams: rams.color[pack][token].value,
						});
					});

					return <PackTable key={pack} pack={pack} tableData={tableData} />;
				})}
			</div>
		</>
	);
}
